Name:           ros-melodic-pr2-navigation-perception
Version:        0.1.28
Release:        1%{?dist}
Summary:        ROS pr2_navigation_perception package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_navigation_perception
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-filters
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-laser-filters
Requires:       ros-melodic-laser-geometry
Requires:       ros-melodic-laser-tilt-controller-filter
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-pr2-machine
Requires:       ros-melodic-pr2-navigation-self-filter
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-semantic-point-annotator
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-topic-tools
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-filters
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-laser-filters
BuildRequires:  ros-melodic-laser-geometry
BuildRequires:  ros-melodic-laser-tilt-controller-filter
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-pr2-machine
BuildRequires:  ros-melodic-pr2-navigation-self-filter
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-semantic-point-annotator
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-topic-tools

%description
This package holds navigation-specific sensor configuration options and launch
files for the PR2.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Nov 15 2019 David Feil-Seifer <dave@cse.unr.edu> - 0.1.28-1
- Autogenerated by Bloom

