Name:           ros-hydro-pr2-navigation-perception
Version:        0.1.22
Release:        0%{?dist}
Summary:        ROS pr2_navigation_perception package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_navigation_perception
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-filters
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-laser-filters
Requires:       ros-hydro-laser-geometry
Requires:       ros-hydro-laser-tilt-controller-filter
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-pcl-ros
Requires:       ros-hydro-pr2-machine
Requires:       ros-hydro-pr2-navigation-self-filter
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-semantic-point-annotator
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-tf
Requires:       ros-hydro-topic-tools
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-filters
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-laser-filters
BuildRequires:  ros-hydro-laser-geometry
BuildRequires:  ros-hydro-laser-tilt-controller-filter
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-pcl-ros
BuildRequires:  ros-hydro-pr2-machine
BuildRequires:  ros-hydro-pr2-navigation-self-filter
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-semantic-point-annotator
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-topic-tools

%description
This package holds navigation-specific sensor configuration options and launch
files for the PR2.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Sep 08 2014 Maintained by Eitan Marder-Eppstein <eitan@willowgarage.com> - 0.1.22-0
- Autogenerated by Bloom

